### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=PhpStorm

###
POST http://192.168.5.228:8000/api/login
Content-Type: application/json

{
    "email": "panjidenisgiantoroo5@gmail.com",
    "password": "12345678"
}

###
POST http://192.168.5.228:8000/api/sensor
Content-Type: application/json

{
    "rpm": 0,
    "temperature": 0,
    "vibration": 0,
    "voltage": 0
}

