### GET request to example server
GET https://examples.http-client.intellij.net/get
    ?generated-in=PhpStorm

###
POST http://192.168.5.228:8000/api/login
Content-Type: application/json

{
    "email": "panjidenisgiantoroo5@gmail.com",
    "password": "12345678"
}

###
POST http://103.134.154.111/api/sensor
Content-Type: application/json

{
    "rpm": 1,
    "temperature": 1,
    "vibration": 1,
    "voltage": 1
}

